{
 "title": "Motorhead Cluster (Java)",
 "description": "N.I.B. Motorhead Cluster Stats (Java)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster_api", "label": "Cluster API Server", "query": "marcusolsson-json-datasource" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({cluster=\"$cluster\", nodeid=\"$nodeid\"},instance)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$prometheus_jobname\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$prometheus_jobname\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   },
   { "name": "nodeid", "label": "Node ID", "query": { "query": "label_values(nodeid)" } },
   {
    "name": "motorhead_admin_url",
    "label": "Admin Url",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.status" }
     ],
     "method": "GET",
     "urlPath": "/cluster/status"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes[*].id", "name": "Node Id" },
      { "jsonPath": "$.nodes[*].name", "language": "jsonpath", "name": "Alias" },
      { "jsonPath": "$.nodes[*].host", "language": "jsonpath", "name": "Hostname" },
      { "jsonPath": "$.nodes[*].pid", "language": "jsonpath", "name": "PID" },
      { "jsonPath": "$.nodes[*].initiators", "language": "jsonpath", "name": "Initiators" },
      { "jsonPath": "$.nodes[*].status", "language": "jsonpath", "name": "Status" },
      { "jsonPath": "$.nodes[*].addresses[0]", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "urlPath": "/cluster/status"
    }
   ]
  },
  {
   "title": "Pending Jobs ",
   "type": "table",
   "description": "Jobs waiting to be executed (Input Queue)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$[*].uuid", "name": "UUID" },
      { "jsonPath": "$[*].jobNumber", "language": "jsonpath", "name": "Job Number" },
      { "jsonPath": "$[*].script", "language": "jsonpath", "name": "Script" },
      { "jsonPath": "$[*].jobClass", "language": "jsonpath", "name": "Class" },
      { "jsonPath": "$[*].status", "language": "jsonpath", "name": "Status" }
     ],
     "method": "GET",
     "urlPath": "/job/backlog"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.length" }
     ],
     "method": "GET",
     "urlPath": "/cluster/status"
    }
   ]
  },
  {
   "title": "Job Classes",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$[*].name", "name": "Class" },
      { "jsonPath": "$[*].initiatorsCount", "language": "jsonpath", "name": "Assigned Initiators" },
      { "jsonPath": "$[*].enabled", "language": "jsonpath", "name": "Enabled" }
     ],
     "method": "GET",
     "urlPath": "/class/status"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum by(node) (motorhead_jobs_active{cluster=\"$cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ActiveJobs ",
   "type": "table",
   "description": "Jobs waiting to be executed (Input Queue)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$[*].uuid", "name": "UUID" },
      { "jsonPath": "$[*].jobNumber", "language": "jsonpath", "name": "Job Number" },
      { "jsonPath": "$[*].script", "language": "jsonpath", "name": "Script" },
      { "jsonPath": "$[*].jobClass", "language": "jsonpath", "name": "Class" },
      { "jsonPath": "$[*].status", "language": "jsonpath", "name": "Status" },
      { "jsonPath": "$[*].nodeName", "language": "jsonpath", "name": "Node" },
      { "jsonPath": "$[*].nodeId", "language": "jsonpath", "name": "" },
      { "jsonPath": "$[*].initiatorId", "language": "jsonpath", "name": "Init" }
     ],
     "method": "GET",
     "urlPath": "/job/ps"
    }
   ]
  },
  { "title": "Cluster Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Submit",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$[*].name" }
     ],
     "method": "GET",
     "urlPath": "/class/status"
    }
   ]
  },
  {
   "title": "Job Control",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$[*].name" }
     ],
     "method": "GET",
     "urlPath": "/class/status"
    }
   ]
  },
  {
   "title": "Class Control",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$[*].name" }
     ],
     "method": "GET",
     "urlPath": "/class/status"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Motorhead main log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", job=\"none\"} |= ``"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{cluster=\"$cluster\", uri!~\".*(prometheus|health).*\", }[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{cluster=\"$cluster\", exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{cluster=\"$cluster\", exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(level) (irate(logback_events_total{cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{cluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node JVM Statistics (node $nodeid)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "nodeid",
   "targets": [
    {}
   ]
  },
  {
   "title": "Node ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_info{cluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{cluster=\"$cluster\", nodeid=\"$nodeid\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", nodeid=\"$nodeid\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{jcluster=\"$cluster\", nodeid=\"$nodeid\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", nodeid=\"$nodeid\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{cluster=\"$cluster\", nodeid=\"$nodeid\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "process_files_open_files{cluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "Open Files"
    }
   ]
  },
  {
   "title": "Instance IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_info{cluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "system_cpu_usage{cluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{cluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "Demons@{{node}}"
    },
    {
     "expr": "jvm_threads_live_threads{jcluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "Live@{{node}}"
    },
    {
     "expr": "jvm_threads_peak_threads{cluster=\"$cluster\", nodeid=\"$nodeid\"}",
     "legendFormat": "Peak@{{node}}"
    }
   ]
  }
 ]
}