{
 "title": "Supernaut Cluster (Java)",
 "description": "Dashboard for Supernaut (Java)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": { "query": "label_values(region)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{region=\"$region\"},instance)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{region=\"$region\", instance=\"${instance:glob}\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{region=\"$region\", instance=\"${instance:glob}\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Supernaut Region Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transactions",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(region) (supernaut_transactions_count_total{region=\"$region\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Transaction Time",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(supernaut_transaction_elapsed_seconds_max)  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Transaction Elapsed ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "max by(transid) (supernaut_transaction_elapsed_seconds_max{region=\"$region\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Terminals Connected",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 3, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "sum by(region) (supernaut_terminals_count{region=\"$region\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temporary Storage I/O Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
     "targets": [
      {
       "expr": "delta(supernaut_ts_write_count_total{region=\"$region\"}[1m])",
       "legendFormat": "WRITEQ TS"
      },
      {
       "expr": "delta(supernaut_ts_read_count_total{region=\"$region\"}[1m])",
       "legendFormat": "READQ TS"
      },
      {
       "expr": "delta(supernaut_ts_delete_count_total{region=\"$region\"}[1m])",
       "legendFormat": "DELETEQ TS"
      }
     ]
    },
    {
     "title": "Average Transaction Program Elapsed",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(supernaut_transaction_elapsed_seconds_sum{region=\"$region\"} / supernaut_transaction_elapsed_seconds_count{region=\"$region\"}) by (program)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Transaction Time over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 6 },
     "targets": [
      {
       "expr": "avg by(application) (avg_over_time(supernaut_transaction_elapsed_seconds_max{region=\"$region\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Transaction Elapsed",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 5, "x": 11, "y": 6 },
     "targets": [
      {
       "expr": "avg by(transid) (supernaut_transaction_elapsed_seconds_max{region=\"$region\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File I/O Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
     "targets": [
      {
       "expr": "delta(supernaut_file_write_count_total{region=\"$region\"}[1m])",
       "legendFormat": "WRITE/REWRITE"
      },
      {
       "expr": "delta(supernaut_file_read_count_total{region=\"$region\"}[1m])",
       "legendFormat": "READ*/STARTBR"
      },
      {
       "expr": "delta(supernaut_file_delete_count_total{region=\"$region\"}[1m])",
       "legendFormat": "DELETE"
      }
     ]
    },
    {
     "title": "HTTP Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{region=\"$region\", uri!~\".*(prometheus|health).*\", }[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "HTTP Requests/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{region=\"$region\"}[1m]))",
       "legendFormat": "Requests per second"
      }
     ]
    },
    {
     "title": "HTTP Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{region=\"$region\", exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{region=\"$region\", exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Supernaut Region Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{region=\"$region\"} |= ``"
      }
     ]
    },
    {
     "title": "Logs Statistics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{region=\"$region\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      },
      {
       "expr": "irate(logback_events_total{region=\"$region\", level=\"warn\"}[5m])",
       "legendFormat": "warn"
      },
      {
       "expr": "irate(logback_events_total{region=\"$region\", level=\"error\"}[5m])",
       "legendFormat": "error"
      },
      {
       "expr": "irate(logback_events_total{region=\"$region\", level=\"debug\"}[5m])",
       "legendFormat": "debug"
      },
      {
       "expr": "irate(logback_events_total{region=\"$region\", level=\"trace\"}[5m])",
       "legendFormat": "trace"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Statistics (${instance:glob})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{region=\"$region\", instance=\"${instance:glob}\"}"
      }
     ]
    },
    {
     "title": "Transactions Processed",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "supernaut_transactions_count_total{region=\"$region\", instance=\"${instance:glob}\"}"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{region=\"$region\", instance=\"${instance:glob}\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{region=\"$region\",instance=\"${instance:glob}\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{region=\"$region\", instance=\"${instance:glob}\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{region=\"$region\",instance=\"${instance:glob}\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Process Open Files",
     "type": "graph",
     "gridPos": { "h": 6, "w": 3, "x": 13, "y": 3 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{region=\"$region\", instance=\"${instance:glob}\"}",
       "legendFormat": "Open Files"
      },
      {
       "expr": "process_files_max_files{region=\"$region\", instance=\"${instance:glob}\"}",
       "legendFormat": "Max Files"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{region=\"$region\", instance=\"${instance:glob}\"}*1000"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_cpu_usage{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 9 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"${instance:glob}\", region=\"$region\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 2, "x": 17, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"${instance:glob}\", region=\"$region\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 2, "x": 19, "y": 9 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"${instance:glob}\", region=\"$region\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"${instance:glob}\", region=\"$region\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "Requests/second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{region=\"$region\", instance=\"${instance:glob}\"}[1m]))",
       "legendFormat": "Requests per second"
      }
     ]
    },
    {
     "title": "Requests duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{region=\"$region\", instance=\"${instance:glob}\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{region=\"$region\", instance=\"${instance:glob}\", status!~\"5..\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "max(http_server_requests_seconds_max{region=\"$region\", instance=\"${instance:glob}\", status!~\"5..\"})",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "HTTP Codes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{region=\"$region\", instance=\"${instance:glob}\", status=~\"5..\"}[1m]))",
       "legendFormat": "5xx - Server Errors"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{region=\"$region\", instance=\"${instance:glob}\", status=~\"4..\"}[1m]))",
       "legendFormat": "4xx - Client Errors"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{region=\"$region\", instance=\"${instance:glob}\", status=~\"2..\"}[1m]))",
       "legendFormat": "2xx - Success"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"${instance:glob}\", status=~\"3..\"}[1m]))",
       "legendFormat": "3xx - Redirections"
      }
     ]
    }
   ]
  }
 ]
}