 /*******************************************************************
  * Copyright Amazon.com, Inc. or its affiliates.                   *
  * All Rights Reserved.                                            *
  *                                                                 *
  * Licensed under the Apache License, Version 2.0 (the "License"). *
  * You may not use this file except in compliance with the License.*
  * You may obtain a copy of the License at                         *
  *                                                                 *
  *    http://www.apache.org/licenses/LICENSE-2.0                   *
  *                                                                 *
  * Unless required by applicable law or agreed to in writing,      *
  * software distributed under the License is distributed on an     *
  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,    *
  * either express or implied. See the License for the specific     *
  * language governing permissions and limitations under the License*
  ******************************************************************/
 DCL 1 CCDA_COMMON_MESSAGES,
       2 CCDA_MSG_THANK_YOU    CHAR(50) 
           INIT('Thank you for using CardDemo application...      '),
       2 CCDA_MSG_INVALID_KEY  CHAR(50)
           INIT('Invalid key pressed. Please see below...         ');
