// Welocme customized screen
import { WELCOME } from './templates/WELCOME';
// Error screen
import { ERROR } from './templates/ERROR';

// User screens
import { COACTUP_CACTUPA } from './templates/COACTUP_CACTUPA';
import { COACTVW_CACTVWA } from './templates/COACTVW_CACTVWA';
import { COADM01_COADM1A } from './templates/COADM01_COADM1A';
import { COBIL00_COBIL0A } from './templates/COBIL00_COBIL0A';
import { COCRDLI_CCRDLIA } from './templates/COCRDLI_CCRDLIA';
import { COCRDSL_CCRDSLA } from './templates/COCRDSL_CCRDSLA';
import { COCRDUP_CCRDUPA } from './templates/COCRDUP_CCRDUPA';
import { COMEN01_COMEN1A } from './templates/COMEN01_COMEN1A';
import { CORPT00_CORPT0A } from './templates/CORPT00_CORPT0A';
import { COSGN00_COSGN0A } from './templates/COSGN00_COSGN0A';
import { COTRN00_COTRN0A } from './templates/COTRN00_COTRN0A';
import { COTRN01_COTRN1A } from './templates/COTRN01_COTRN1A';
import { COTRN02_COTRN2A } from './templates/COTRN02_COTRN2A';
import { COUSR00_COUSR0A } from './templates/COUSR00_COUSR0A';
import { COUSR01_COUSR1A } from './templates/COUSR01_COUSR1A';
import { COUSR02_COUSR2A } from './templates/COUSR02_COUSR2A';
import { COUSR03_COUSR3A } from './templates/COUSR03_COUSR3A';
import { COMEN01_COMEN1A_NIB } from './templates/COMEN01_COMEN1A_NIB';
import { COSGN00_COSGN0A_NIB } from './templates/COSGN00_COSGN0A_NIB';

export const TEMPLATE_IMPORTS = [
  WELCOME,
  ERROR,
  COACTUP_CACTUPA,
  COACTVW_CACTVWA,
  COADM01_COADM1A,
  COBIL00_COBIL0A,
  COCRDLI_CCRDLIA,
  COCRDSL_CCRDSLA,
  COCRDUP_CCRDUPA,
  COMEN01_COMEN1A,
  CORPT00_CORPT0A,
  COSGN00_COSGN0A,
  COTRN00_COTRN0A,
  COTRN01_COTRN1A,
  COTRN02_COTRN2A,
  COUSR00_COUSR0A,
  COUSR01_COUSR1A,
  COUSR02_COUSR2A,
  COUSR03_COUSR3A,
  COMEN01_COMEN1A_NIB,
  COSGN00_COSGN0A_NIB
] as const;

export const TEMPLATE_REGISTRY = {
  WELCOME,
  ERROR,
  COACTUP_CACTUPA,
  COACTVW_CACTVWA,
  COADM01_COADM1A,
  COBIL00_COBIL0A,
  COCRDLI_CCRDLIA,
  COCRDSL_CCRDSLA,
  COCRDUP_CCRDUPA,
  COMEN01_COMEN1A,
  CORPT00_CORPT0A,
  COSGN00_COSGN0A,
  COTRN00_COTRN0A,
  COTRN01_COTRN1A,
  COTRN02_COTRN2A,
  COUSR00_COUSR0A,
  COUSR01_COUSR1A,
  COUSR02_COUSR2A,
  COUSR03_COUSR3A,
  COMEN01_COMEN1A_NIB,
  COSGN00_COSGN0A_NIB
} as const;
