# Jcls folder, Spring Batch default is jcl-root
# TODO: environment variable support - below doesnt work
# jclsFolder=${NIB_JAVA_HOME}/samples/aws-carddemo-iscobol/jcl-root

# Sequential files folder, default is ${jclsRoot}/files
#filesFolder="${jclsRoot}/files"

# Embedded memory folder, default is ${filesFolder}/embedded
#embeddedFolder="${filesFolder}/embedded"

# SYSIN expected record format, default is LSEQ
#sysin.recordFormat=FB

# SYSIN expected record size, default is 0
sysin.recordSize=80

# SYSOUT folder, default is ${jclsRoot}/sysout
#sysoutFolder="${jclsRoot}/sysout"

# Temporary files folder
#tempFolder="${jclsRoot}/temp"

# Files with a different definition catalog vs DCB, possible values are:
#
# dcb (default) : the DCB info is used, a warning message is emitted at the first usage
# catalog       : the catalog info is used, a warning message is emitted at the first usage
# abend         : JOB abends
#  
#fileDefMismatch=dcb

# Create missing required files (disposition OLD / SHR), default is false  
#createMissingRequiredFiles=false

# SYSOUT output is line sequential, default is false  
#sysoutLineSequential=false

# Keep temporary files after the JOB execution, default is false  
#keepTempFiles=false

# Abend return code, default is 255
#abendExitCode=255

# Default JOB MSGCLASS, default is blank
#defaultJobMessageClass="" 

# Default JOB DATACLAS, default is blank
#defaultJobDataclass="" 

# SYSOUT class handler
#sysout.handler.A=mySysoutHandlerClassA 
#sysout.handler.B=mySysoutHandlerClassB 

# SYSOUT class destination path
#sysout.path.A=mySysoutHandlerClassA 
#sysout.path.B=mySysoutHandlerClassB 

# Environment charset, default is: ISO8859_1
#environment.charset=ISO8859_1

# Files charset, default is: ${environment.charset}
#file.charset=${application.charset}

# Database charset, default is: ${environment.charset}
#database.charset=${application.charset}

# Console charset, default is: ISO8859_1
#console.charset=${environment.charset}

# Files new line separator, default is: System.lineSeparator()
# accepted values are: \n (Linux\Unix compliant) or \r\n (Windows compliant) 
#file.lineseparator=

# File page size for ASA, default is 24
file.pageSize=43

# File access is buffered, default is true
#file.bufferedaccess=true

# DB connection
#database.driver=com.mysql.cj.jdbc.Driver
#database.url=jdbc:mysql://root:mysql@localhost:3307/vsam
#database.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#database.url=jdbc:sqlserver://localhost;database=vsam;user=vsam;password=vsam;encrypt=false
database.driver=org.postgresql.Driver
database.url=jdbc:postgresql://localhost/postgres?user=postgres&password=postgres&ssl=false&currentSchema=vsam
#database.url=jdbc:mysql://root:mysql@localhost:3307/vsam
#database.url=jdbc:db2://localhost:50000/DARKSIDE:user=db2inst1;password=darkside;currentSchema=VSAM

# Load packages for user programs, use : to separate multiple packages, i.e.:
# com.company.project.lib1:com.company.project.lib2:com.company.project.lib3
loadlib=com.nib.demoapp:com.nib.demoapp.calls

