events {
    worker_connections   1024;
}

http {
    upstream motorhead {
        least_conn;
        server motorhead-a:8080;
        server motorhead-b:8080;
        server motorhead-cde:8080;
    }

    server {
        listen 8081;
        location / {
        proxy_pass http://motorhead;
        }
    }
}