events {
    worker_connections   1024;
}

http {
    upstream supernaut {
        least_conn;
        server supernaut:8080;
    }

    server {
        listen 8080;
        location / {
        proxy_pass http://supernaut;
        }
    }
}